#DISCLAMER - some parts of this code are copy-pasted in the attempts to make it work! Even though they
#are not my own, I took time to understand how and why it works!

version: 2
jobs:
  build:
    working_directory: ~/MobileAppAutomationTest/AndroidDemo
    docker:
      - image: circleci/android@sha256:5cdc8626cc6f13efe5ed982cdcdb432b0472f8740fed8743a6461e025ad6cdfc
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout:
          path: ~/MobileAppAutomationTest
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: |
            yes | sdkmanager --licenses || exit 0
            yes | sdkmanager --update || exit 0
            ./gradlew androidDependencies
      - run:
          name: Setup Android emulator
          command: |
            # echo "Listing of /opt/android/sdk"
            # ls /opt/android/sdk
            set -e
            sdkmanager "system-images;android-21;default;armeabi-v7a"
            echo "no" | avdmanager create avd -n test -k "system-images;android-21;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true

      - run:
          name: Wait for emulator
          command: circle-android wait-for-boot

      - run:
          name: Run EspressoTests
          command: ./gradlew connectedAndroidTest

      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
